const screenWidth = 1080;
const screenHeight = 900;

const gridWidth = 60;
const gridHeight = 60;

const gridColumns = 19;
const gridRows = 16;

const mapGridOriginal = [
  [
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: true, occupants: [] },
    { valid: false, occupants: [] },
  ],
  [
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
    { valid: false, occupants: [] },
  ],
];
